CREATE TABLE menu (
id_menu INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
nombre VARCHAR(15) NOT NULL,
num_personas INT DEFAULT 0
);

CREATE TABLE dia (
fecha DATE NOT NULL PRIMARY KEY,
temperatura DOUBLE NOT NULL,
menu INT NOT NULL,
FOREIGN KEY (menu)
REFERENCES menu (id_menu)
ON DELETE CASCADE
ON UPDATE CASCADE
);

CREATE TABLE plato (
nombre VARCHAR(50) NOT NULL PRIMARY KEY,
descripcion VARCHAR(100),
tipo VARCHAR(10) NOT NULL
);

CREATE TABLE contiene (
menu INT,
plato VARCHAR(50) NOT NULL,
cantidad INT,
PRIMARY KEY (menu, plato),
FOREIGN KEY (menu)
REFERENCES menu (id_menu)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY (plato)
REFERENCES plato (nombre)
ON DELETE CASCADE
ON UPDATE CASCADE
);